### PR TITLE
conf: Dockerized API & MySQL container

### PR DESCRIPTION
**Pull request by bthorng**
## Context
Made the API work run on a Docker container and be able to communicate with another container running MySQL.

## Changes
- Added docker-compose.yaml
- Added setup SQL scripts in the resource folder
- Changed application settings to be able to locate the Docker container

## Things to note
On first startup, the SQL scripts will be run from the resource folder and a data folder will be created in the root directory. If you want to start fresh with the mock data specified in the SQL scripts only again, delete the data folder and `docker-compose up` again. This _should_ get rid of data you've added and use only the records specified in the SQL script.

### CODE REVIEW

**Comment by bthorng** [comment]
Also, please change the Product schema to match your needs @Dratorz

**Comment by bthorng** [comment]
🐍 🐍 🐍 🐍 🐍 🐍 🐍 🐍 🐍 🐍 🐍 🐍 🐍 🐍 🐍 🐍 🐍 🐍 🐍 🐍 🐍 🐍 🐍 🐍 🐍 🐍 🐍 🐍 🐍 🐍 🐍 🐍 🐍 🐍

**Comment by bthorng** [comment]
Everything seems to now be working (CRUD works, all tests pass).
Please test out the branch when you can.
Also, for bar codes, @Dratorz consider using generated UID's instead of specifying them in the POST body

**Review by Dratorz — APPROVED** [review]
Finally on docker!

**Review by harifuda — APPROVED** [review]
Great work!

**Review by jumpung — APPROVED** [review]
This pr was good

**Pull request merged**
